// verification-packs/frontend-72-route-formal-equivalence-v1/formal-campaign/engine/profiles/svelte/project/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { routes } from "./routes";
  let path = window.location.pathname;
  let page = routes.find(route => route.path === path) ?? routes[0];
  function navigate(event: MouseEvent, next: string) { event.preventDefault(); history.pushState({}, "", next); path = next; page = routes.find(route => route.path === path) ?? routes[0]; }
  onMount(() => { const listener = () => { path = window.location.pathname; page = routes.find(route => route.path === path) ?? routes[0]; }; window.addEventListener("popstate", listener); return () => window.removeEventListener("popstate", listener); });
</script>
<div class="shell"><nav class="nav" aria-label="主要导航">
  <strong>ELMOS 有界导航验证</strong>
  {#each routes as route}<a data-route-id={route.id} data-requires-auth={route.requiresAuth} data-deep-link={route.deepLink} href={route.path} onclick={(event) => navigate(event, route.path)}>{route.title}</a>{/each}
</nav><main class="content" id="main" data-route-id={page?.id} data-route-path={page?.path} data-requires-auth={page?.requiresAuth} data-deep-link={page?.deepLink}><article class="card">
  <h1>{page?.title}</h1><p>{page?.text}</p>
  <p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p>
</article></main></div>

// client-packs/frontend-72-route-equivalence-v1/formal-campaign/engine/profiles/react/project/src/App.tsx
import { NavLink, Navigate, Route, Routes } from "react-router-dom";
import { routes, type GeneratedRoute } from "./routes";
import "./styles.css";

function GeneratedPage({ route }: { readonly route: GeneratedRoute }) {
  return <main className="content" id="main" data-route-id={route.id} data-route-path={route.path} data-requires-auth={route.requiresAuth} data-deep-link={route.deepLink}><article className="card">
    <h1>{route.title}</h1><p>{route.text}</p>
    <p className="status" role="status">生成状态：等待真实浏览器与可访问性验证</p>
  </article></main>;
}

export function App() {
  return <div className="shell">
    <nav className="nav" aria-label="主要导航"><strong>ELMOS 有界导航验证</strong>
      {routes.map(route => <NavLink key={route.id} to={route.path} data-route-id={route.id} data-requires-auth={route.requiresAuth} data-deep-link={route.deepLink}>{route.title}</NavLink>)}
    </nav>
    <Routes>
      {routes.map(route => <Route key={route.id} path={route.path} element={<GeneratedPage route={route} />} />)}
      <Route path="*" element={<Navigate to={routes[0]?.path ?? "/"} replace />} />
    </Routes>
  </div>;
}
