// client-packs/frontend-72-route-equivalence-v2/formal-campaign/artifacts/engine/profiles/vue3/project/src/App.vue
<script setup lang="ts">import { routes } from "./routes"; import ElmosInteractionPanel from "./ElmosInteractionPanel.vue";</script>
<template><div class="shell"><nav class="nav" aria-label="主要导航">
  <strong>ELMOS 有界前端交互验证</strong>
  <RouterLink v-for="route in routes" :key="route.id" :to="route.path" :data-route-id="route.id" :data-requires-auth="route.requiresAuth" :data-deep-link="route.deepLink">{{ route.title }}</RouterLink>
</nav><RouterView /><ElmosInteractionPanel /></div></template>

// verification-packs/frontend-72-route-formal-equivalence-v2/formal-campaign/artifacts/engine/profiles/angular/project/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";
import { ELMOS_ROUTES } from "../elmos-bounded-navigation";
import { ElmosInteractionComponent } from "../elmos-interaction.component";
@Component({
  standalone: true, selector: "app-root", imports: [RouterLink, RouterOutlet, ElmosInteractionComponent],
  template: `<div class="shell"><nav class="nav" aria-label="主要导航"><strong>ELMOS 有界前端交互验证</strong>@for (route of routes; track route.id) {<a [routerLink]="route.path" [attr.data-route-id]="route.id" [attr.data-requires-auth]="route.requiresAuth" [attr.data-deep-link]="route.deepLink">{{ route.title }}</a>}</nav><router-outlet /><elmos-interaction /></div>`,
})
export class AppComponent { readonly routes = ELMOS_ROUTES; }
