// client-packs/frontend-72-route-equivalence-v2/formal-campaign/artifacts/engine/profiles/angular/project/src/app/generated-page.component.ts
import { Component } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
@Component({
  standalone: true,
  selector: "app-generated-page",
  template: `<main class="content" id="main" data-elmos-active-route="true" data-elmos-active-component="true" [attr.data-elmos-route-id]="id" [attr.data-elmos-route-path]="path" [attr.data-elmos-requires-auth]="requiresAuth" [attr.data-elmos-deep-link]="deepLink" data-elmos-component-id="interaction.shell" [attr.data-elmos-component-key]="id" [attr.data-route-id]="id" [attr.data-route-path]="path" [attr.data-requires-auth]="requiresAuth" [attr.data-deep-link]="deepLink"><article class="card"><h1>{{ title }}</h1><p>{{ text }}</p><p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p></article></main>`,
})
export class GeneratedPageComponent {
  readonly id = String(this.route.snapshot.data["id"] ?? "");
  readonly path = String(this.route.snapshot.data["path"] ?? "");
  readonly title = String(this.route.snapshot.data["title"] ?? "");
  readonly text = String(this.route.snapshot.data["text"] ?? "");
  readonly requiresAuth = Boolean(this.route.snapshot.data["requiresAuth"]);
  readonly deepLink = Boolean(this.route.snapshot.data["deepLink"]);
  constructor(private readonly route: ActivatedRoute) {}
}

// verification-packs/frontend-72-route-formal-equivalence-v2/formal-campaign/artifacts/engine/profiles/vue3/project/src/views/GeneratedPage.vue
<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";
import { routes } from "../routes";
const current = useRoute();
const page = computed(() => routes.find(route => route.path === current.path) ?? routes[0]);
</script>
<template><main class="content" id="main" data-elmos-active-route="true" data-elmos-active-component="true" :data-elmos-route-id="page?.id" :data-elmos-route-path="page?.path" :data-elmos-requires-auth="page?.requiresAuth" :data-elmos-deep-link="page?.deepLink" data-elmos-component-id="interaction.shell" :data-elmos-component-key="page?.id" :data-route-id="page?.id" :data-route-path="page?.path" :data-requires-auth="page?.requiresAuth" :data-deep-link="page?.deepLink"><article class="card">
  <h1>{{ page?.title }}</h1><p>{{ page?.text }}</p>
  <p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p>
</article></main></template>
