// client-packs/frontend-72-route-equivalence-v1/formal-campaign/engine/profiles/angular/project/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";
import { ELMOS_ROUTES } from "../elmos-bounded-navigation";
@Component({
  standalone: true, selector: "app-root", imports: [RouterLink, RouterOutlet],
  template: `<div class="shell"><nav class="nav" aria-label="主要导航"><strong>ELMOS 有界导航验证</strong>@for (route of routes; track route.id) {<a [routerLink]="route.path" [attr.data-route-id]="route.id" [attr.data-requires-auth]="route.requiresAuth" [attr.data-deep-link]="route.deepLink">{{ route.title }}</a>}</nav><router-outlet /></div>`,
})
export class AppComponent { readonly routes = ELMOS_ROUTES; }

// verification-packs/frontend-72-route-formal-equivalence-v1/formal-campaign/engine/profiles/vue2/project/src/App.vue
<script>
import { routes } from "./routes";
export default { data: () => ({ routes }) };
</script>
<template><div class="shell"><nav class="nav" aria-label="主要导航">
  <strong>ELMOS 有界导航验证</strong>
  <RouterLink v-for="route in routes" :key="route.id" :to="route.path" :data-route-id="route.id" :data-requires-auth="route.requiresAuth ? 'true' : 'false'" :data-deep-link="route.deepLink ? 'true' : 'false'">{{ route.title }}</RouterLink>
</nav><RouterView /></div></template>
