// client-packs/frontend-72-route-equivalence-v2/formal-campaign/artifacts/engine/profiles/angular/project/src/app/generated-page.component.ts
import { Component } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
@Component({
  standalone: true,
  selector: "app-generated-page",
  template: `<main class="content" id="main" data-elmos-active-route="true" data-elmos-active-component="true" [attr.data-elmos-route-id]="id" [attr.data-elmos-route-path]="path" [attr.data-elmos-requires-auth]="requiresAuth" [attr.data-elmos-deep-link]="deepLink" data-elmos-component-id="interaction.shell" [attr.data-elmos-component-key]="id" [attr.data-route-id]="id" [attr.data-route-path]="path" [attr.data-requires-auth]="requiresAuth" [attr.data-deep-link]="deepLink"><article class="card"><h1>{{ title }}</h1><p>{{ text }}</p><p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p></article></main>`,
})
export class GeneratedPageComponent {
  readonly id = String(this.route.snapshot.data["id"] ?? "");
  readonly path = String(this.route.snapshot.data["path"] ?? "");
  readonly title = String(this.route.snapshot.data["title"] ?? "");
  readonly text = String(this.route.snapshot.data["text"] ?? "");
  readonly requiresAuth = Boolean(this.route.snapshot.data["requiresAuth"]);
  readonly deepLink = Boolean(this.route.snapshot.data["deepLink"]);
  constructor(private readonly route: ActivatedRoute) {}
}

// verification-packs/frontend-72-route-formal-equivalence-v2/formal-campaign/artifacts/engine/profiles/vue2/project/src/views/GeneratedPage.vue
<script>
import { routes } from "../routes";
export default { computed: { page() { return routes.find(route => route.path === this.$route.path) || routes[0]; } } };
</script>
<template><main class="content" id="main" data-elmos-active-route="true" data-elmos-active-component="true" :data-elmos-route-id="page && page.id" :data-elmos-route-path="page && page.path" :data-elmos-requires-auth="page && page.requiresAuth ? 'true' : 'false'" :data-elmos-deep-link="page && page.deepLink ? 'true' : 'false'" data-elmos-component-id="interaction.shell" :data-elmos-component-key="page && page.id" :data-route-id="page && page.id" :data-route-path="page && page.path" :data-requires-auth="page && page.requiresAuth ? 'true' : 'false'" :data-deep-link="page && page.deepLink ? 'true' : 'false'"><article class="card">
  <h1>{{ page && page.title }}</h1><p>{{ page && page.text }}</p>
  <p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p>
</article></main></template>
