// client-packs/frontend-72-route-equivalence-v1/formal-campaign/engine/profiles/angular/project/src/app/generated-page.component.ts
import { Component } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
@Component({
  standalone: true,
  selector: "app-generated-page",
  template: `<main class="content" id="main" [attr.data-route-id]="id" [attr.data-route-path]="path" [attr.data-requires-auth]="requiresAuth" [attr.data-deep-link]="deepLink"><article class="card"><h1>{{ title }}</h1><p>{{ text }}</p><p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p></article></main>`,
})
export class GeneratedPageComponent {
  readonly id = String(this.route.snapshot.data["id"] ?? "");
  readonly path = String(this.route.snapshot.data["path"] ?? "");
  readonly title = String(this.route.snapshot.data["title"] ?? "");
  readonly text = String(this.route.snapshot.data["text"] ?? "");
  readonly requiresAuth = Boolean(this.route.snapshot.data["requiresAuth"]);
  readonly deepLink = Boolean(this.route.snapshot.data["deepLink"]);
  constructor(private readonly route: ActivatedRoute) {}
}

// client-packs/frontend-72-route-equivalence-v1/formal-campaign/engine/profiles/vue2/project/src/views/GeneratedPage.vue
<script>
import { routes } from "../routes";
export default { computed: { page() { return routes.find(route => route.path === this.$route.path) || routes[0]; } } };
</script>
<template><main class="content" id="main" :data-route-id="page && page.id" :data-route-path="page && page.path" :data-requires-auth="page && page.requiresAuth" :data-deep-link="page && page.deepLink"><article class="card">
  <h1>{{ page && page.title }}</h1><p>{{ page && page.text }}</p>
  <p class="status" role="status">生成状态：等待真实浏览器与可访问性验证</p>
</article></main></template>
